### ISSUE TITLE
Update PHP CS so it support PHP 7 syntax

### ISSUE THREAD

**Issue by windaishi** [pickware/style-guide#58]
The PHP CS should be updated so it supports new PHP 7 syntax like this:

```php
$foo = new class() extends Bar {};
```

**Comment by fixpunkt** [comment]
Das sollte mittlerweile gehen, muss nochmal jemand verifizieren.

**Comment by hanneswernery** [comment]
Wir nutzen bereits die neuste PHPcs version und unterstützen den oben genannten syntax
```
            "name": "squizlabs/php_codesniffer",
            "version": "3.6.0",
```
